### ISSUE TITLE
How to set up arcgis js in my webpack config.

### ISSUE THREAD

**Issue by CHQGIT** [lobsteropteryx/esri-webpack-typescript#5] opened 2016-09-02 16:05 UTC
Hello,
Im pretty new on this webpack worlds and i need some help to set up the arcgis js api in my webpack.config,js.

Im developing an app with:
React,
Webpack dev server
Gulp

I have the following config in my webpack file:

> var path = require('path');
> var esri = require('esri');
> 
> module.exports = {
>   entry: {
>     login: './static/js/bundles/login.js',
>     dashboard: './static/js/bundles/dashboard.js,
> .... //more modules here 
> 
>   },
>   output: {
>     path: path.join(path.join(__dirname, 'dist'), 'js'),
>     filename: '[name].js'
>   },
>   devServer: {
>     inline: true,
>     port: 443,
>     host: "127.0.0.1"
>   },
>   module: {
>     loaders: [
>      {
>        test: /.(js|jsx)$/,
>        exclude: /node_modules/,
>        loader: 'babel',
>        query: {
>          presets: ['react', 'es2015', 'stage-2']
>        }
>      }
>    ]
>  },
>  externals: [
>      function(context, request, callback) {
>          if (/^dojo/.test(request) ||
>              /^dojox/.test(request) ||
>              /^dijit/.test(request) ||
>              /^esri/.test(request)
>          ) {
>              return callback(null, "amd " + request);
>          }
>          callback();
>      }
>  ]
> };

What else i need to do? I have read a lot of githubs but i still dont know how to do it.

In my index,html page i have the api in this way:
 <script src="arcgis_js_api/library/3.16/3.16/init.js"></script>
Cuz i installed it following the tutorial, editing the dojo and init js files and putting the url from my server, in this case localhost:443 where wp server is being loaded.

When i start the server with npm run start i have the following error:

> cannot fin module 'esri'

So how i set up the arcgis api with the config that i have using webpack step by step?

Thanks in advice for ur help!

**Comment by darklilium** [comment] 2016-09-02 16:31
I will put and example app that i have set up in this repo:

https://github.com/darklilium/CHQAves

**Comment by tomwayson** [comment] 2016-09-05 15:31
remove this line, it is not valid, and does not appear to be used: `var esri = require('esri');`

Esri modules are not exposed as CommonJS, nor are they installed in node_modules, so you cannon statically require them.

**Comment by darklilium** [comment] 2016-09-05 15:44
OK. 
I am a little bit confused.
Let me explain my situation.
I want to use the arcgis js api using the es6 import like i have been using for modules that i have in node_modules, something like this: 
Import Map from 'esri/Map';

If i do that, having my api installed as the guideline that the API has (not using CDN) it doesnt work.
The way im loading the modules is using the legacy code that the arcgis api has (i know is not good to do it in this way:  for example: var layer = new esri.layers.FeatureLayer({the code...});

I have my repo here: https://github.com/darklilium/CHQAves thats the enviroment what im using right now.
Is there a way to use the arcgis js api doing some changes in the webpack.config.js file to be able to use the api completely? cuz if i use the legacy mode (how i have been using it) there are some functions and widgets that the api has that i cannot use (for example : BaseMapGallery);

I hope u can help me getting this done, and thanks in advice.

**Comment by tomwayson** [comment] 2016-09-05 18:14
Did you try my above suggestion? Did that fix the 'cannot fin module 'esri'' error?

**Comment by darklilium** [comment] 2016-09-05 18:14
Yes.

**Comment by tomwayson** [comment] 2016-09-05 18:17
OK. Good.

Are you still having problems, other errors?

**Comment by darklilium** [comment] 2016-09-05 18:19
I have the following when for example i want to do this in a jsx file to use the api:
import FeatureLayer from 'esri/layers/FeatureLayer'; 

 Uncaught ReferenceError: **WEBPACK_EXTERNAL_MODULE_484** is not defined

**Comment by darklilium** [comment] 2016-09-05 18:21
My webpack config is like this now:

> var path = require('path');
> 
> module.exports = {
>   entry: {
>     login: './static/js/bundles/login.js',
>     dashboard: './static/js/bundles/dashboard.js',
>     interruptions: './static/js/bundles/interruptions.js',
>     apchq: './static/js/bundles/apchq.js',
>     factigisDashboard: './static/js/bundles/factigisDashboard.js',
>     factigisBackoffice: './static/js/bundles/factigisBackoffice.js',
>     factigisFrontoffice: './static/js/bundles/factigisFrontoffice.js',
>     factigisBackoffice2: './static/js/bundles/factigisBackoffice2.js',
>     apdashboard: './static/js/bundles/apdashboard.js',
>     apmenu: './static/js/bundles/apmenu.js',
>     factigisCarta: './static/js/bundles/factigisCarta.js'
> 
>   },
>   output: {
>     path: path.join(path.join(__dirname, 'dist'), 'js'),
>     filename: '[name].js'
>   },
>   devServer: {
>     inline: true,
>     port: 443,
>     host: "127.0.0.1"
>   },
>   module: {
>     loaders: [
>      {
>        test: /.(js|jsx)$/,
>        exclude: /node_modules/,
>        loader: 'babel',
>        query: {
>          presets: ['react', 'es2015', 'stage-2']
>        }
>      }
>    ]
>  },
> 
>  externals: [
>      function(context, request, callback) {
>          if (/^dojo/.test(request) ||
>              /^dojox/.test(request) ||
>              /^dijit/.test(request) ||
>              /^esri/.test(request)
>          ) {
>             console.log(request);
>              return callback(null, "amd " + request);
>          }
>          callback();
>      }
>  ]
> };

**Comment by tomwayson** [comment] 2016-09-05 19:00
Did you try my suggestion here:

https://geonet.esri.com/message/632846-re-load-amd-modules-in-es6-way?commentID=632846&et=watches.email.thread#comment-632445

It does not appear that the repo that you link to above is a fork of this repo.

I believe the contributors here are more likely to be able to help you if you are starting from a fork of this repo.

**Comment by darklilium** [comment] 2016-09-05 19:10
Well i clone that repo and im trying to figure out what i need to do, but there are some config i dont use and i dont understand (i dont use typescript, for example) so idk how to adapt my code for that app to that..
I have been searching for any resolution to my problem but i still dont find what im looking for.
And also idk where to ask...

Anyways , thx for ur help.

**Comment by tomwayson** [comment] 2016-09-06 06:56
I see. Yes, if you are unfamiliar with, or do not want to use TypeScript, then it can be challenging to get started with this repo.

I have created a fork that shows the base configuration to load ArcGIS API for JavaScript (3.x) modules in webpack using es2105 and babel instead of typescript:

https://github.com/tomwayson/esri-webpack/tree/es2015

I could not get the karma test configuration to work, so I stripped it out of there for now just to show the simplest possible set up. 

That does not include react, Sass, nor any of the other bells and whistles that it looks like you plan on using in your project, but hopefully you can use that as a base that you can build upon to add those.

**Comment by darklilium** [comment] 2016-09-06 12:26
OK Im going to try it and see how i can set up my config.
Thanks for all ur help, if i have some any other questions i will repost here :)

**Comment by lobsteropteryx** [comment] 2016-09-06 12:51
Sorry I missed this, been away for a while.

@darklilium:  The other thing that may be worth looking at is the new app scaffolding from Facebook:  https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html

Should be relatively easy to start with that, "eject" out of the starter app, then add the ESRI libs as externals in your webpack config.

**Comment by darklilium** [comment] 2016-09-06 13:06
How should i add the esri lib as externals? Cuz I saw the example with jquery in the webpack web but i quite dont understand how they do it.

Another question, is there any difference if i installed the arcgis api lib as they said in the tutorial? i mean im not using CDN as u are, i installed the lib modifying the dojo and init.js files with the localhost:443 where i set up my webpack server in the config and then i add the script tag in the html.

**Comment by lobsteropteryx** [comment] 2016-09-06 13:10
Using `externals` should work whether you're pulling from CDN or not; you're basically just telling webpack not to bundle those files.  The relevent section in the webpack config is:

```
externals: [
        function(context, request, callback) {
            if (/^dojo/.test(request) ||
                /^dojox/.test(request) ||
                /^dijit/.test(request) ||
                /^esri/.test(request)
            ) {
                return callback(null, "amd " + request);
            }
            callback();
        }
    ]
```

**Comment by darklilium** [comment] 2016-09-06 13:15
i remember i add that code in my webpack config file, but after that i dont know how to , for example, call the api features as "import Map from 'esri/Map'.
I noticed in your code something that i dont use, like in the index.html u require the bundles main and vendor. Is that necessary? cuz in my config i just add the bundle directly as a compiled file  with the script tag for each html webpage im making.

**Comment by lobsteropteryx** [comment] 2016-09-06 13:20
It's not necessary; we're only doing that because the webpack output is set to `amd`.  You may need to [change](https://webpack.github.io/docs/configuration.html#output-librarytarget) that if you want just use a script tag.

Also, many of the ESRI libs don't seem to be compliant with the ES6 import syntax; I'm not sure if this is a TypeScript thing only, but we had to use

`import Map = require("esri/map");`  

to get the imports to work properly.

**Comment by darklilium** [comment] 2016-09-06 14:00
Ok, i have my demo repo here https://github.com/darklilium/ReactWPackArcGisJS
but im having some problem with an error, it says: 
login.js:1 Uncaught ReferenceError: webpackJsonp is not defined

**Comment by lobsteropteryx** [comment] 2016-09-06 14:53
I'd guess that error is caused by the chunking plugin; you can take that part out of the webpack config if you're not using it.

And it may be that _have_ to set the webpack output to AMD; I'm not sure if you'll be able to consume the ESRI libs any other way.

**Comment by tomwayson** [comment] 2016-09-06 14:59
> in the index.html u require the bundles main and vendor. Is that necessary? 

Yes, that is necessary. 

> And it may be that have to set the webpack output to AMD; I'm not sure if you'll be able to consume the ESRI libs any other way.

That is correct. You must output to AMD, or I guess UMD, but it _must_ be a format that can be  loaded by Dojo's loader via a require statement in index.html. Dojo's AMD loader is going to load all the modules in the application.

> im not using CDN as u are

do you have a reason to do that? If not, you should at least start by using the CDN as it will be easier to get working

> i installed the lib modifying the dojo and init.js files with the localhost:443 where i set up my webpack server in the config and then i add the script tag in the html.

Do you mean, you're following the pattern described in the ["Download" section of the Get the ArcGIS API for JavaScript guide](https://developers.arcgis.com/javascript/3/jshelp/intro_accessapi.html)? If so, that should, in theory, work the same as w/ the CDN. So, again, I'd start w/ the CDN, get it working, then point to your local build of the ArcGIS API for JavaScript.

However, just to be clear, I would not follow the patterns in the "Using Bower for Custom Builds" section of that document w/ the type of webpack configuration (based on using `externals` for esri and dojo modules and outputting to AMD) that we are using here. The modules in the bower build are meant to be built w/ the Dojo build system. It _may_ be possible to load and bundle those w/ [Nordth/dojo-webpack-loader](https://github.com/Nordth/dojo-webpack-loader), however, I'm not aware that anyone has successfully done that yet.

> Also, many of the ESRI libs don't seem to be compliant with the ES6 import syntax; I'm not sure if this is a TypeScript thing only, but we had to use `import Map = require("esri/map");` to get the imports to work properly.

Yes, that is a typescript thing. I'm not sure why, but you have to use that syntax to load esri modules, but only from TypeScript. You can see that [I am using the regular ES2015 imports/exports syntax w/ babel](https://github.com/tomwayson/esri-webpack/blob/es2015/src/app/main.js#L1).

**Comment by darklilium** [comment] 2016-09-06 15:59
OK.
Yea, im using the pattern described in the download section of the api cuz here the internet has too much limitations, so i prefer to have ir locally.

I set up one example on my [repo](https://github.com/darklilium/ReactWPackArcGisJS) and when i tried to use ReactDom to render one component, gives me some error: 

![image](https://cloud.githubusercontent.com/assets/8507515/18281109/fc1c9fc8-7431-11e6-88ea-9949e88e9124.png)

(BTW the api works, cuz w/o that i was able to load a map, now i want to add a component made with react but idk whats the problem.

login.js

> import React from 'react';
> import ReactDOM from 'react-dom';
> import LoginApp from '../components/Login.jsx';
> 
> ReactDOM.render(<LoginApp />, document.getElementById('myLogin'));

Login.jsx

> import React from 'react';
> import Map from "esri/map";
> 
> class LoginApp extends React.Component {
>   constructor(){
>     super();
>   }
>   componentWillMount(){
>     var map = new Map("map_content", {basemap: "streets"});
>   }
>   render(){
>     return (
>         <div className="login_wrapper_content">
>           <div id="map_content"></div>
>         </div>
>     );
>   }
> }
> export default LoginApp;

So what will be the problem?

Thanks for all ur help, in little by little understand the config that i have to have in my app.
Now i need to fix that.

**Comment by tomwayson** [comment] 2016-09-06 16:37
I'm glad you've been able to get past the esri module loading issues. It now looks like you're getting into issues w/ how to use React w/ the ArcGIS API for JavaScript, which means I'm not likely to be much help b/c I don't use react. That said, glancing at the above code, I don't see where the dom node w/ id `map_content` is defined. I'm guessing you need to return that from the from the login component's `render()`?

Either way, now that you've got the modules loading, you should probably be able to follow the patterns that @odoe [has established for using the ArcGIS API for JavaScript w/ React](https://github.com/odoe/esrijs-resources#reactjs) even if he's not using webpack to bundle the app modules, so I don't think this thread is really the best place to solve that issue.

I suggest you open an issue for this on your own repo, include the error message you're seeing, and ping the react devs from this repo and/or link to it from your [GeoNet question about react](https://geonet.esri.com/thread/172884) so that you get the right people looking at it.

**Comment by darklilium** [comment] 2016-09-06 16:41
Oh i solved it.
It was missing this in the webpack.config.js
query: {
         presets: ['react', 'es2015', 'stage-2']
       }

Thanks for all ur help, i will follow your recommendation :)

**Comment by tomwayson** [comment] 2016-09-06 16:49
Great, glad you worked it out!

I'm also really glad that you set that repo up as a generic esri+webpack+es2015+react configuration. I think a lot of people will find that useful.

I suggest closing this issue and opening up any further issues over there.

**Closed as completed** 2016-09-07 12:23 UTC

**Comment by dcworldwide** [comment] 2019-02-27 06:32
Will externals and libtarget amd still work with webpack 4+ and arcgisjs 3.x? We are stuck on that version for now but want to upgrade webpack

**Comment by lobsteropteryx** [comment] 2019-02-27 15:01
@dcworldwide I can't speak to that; you might want to look at some of the work @tomwayson has done with esri-loader.  See the [readme](https://github.com/lobsteropteryx/esri-webpack-typescript/blob/3.x/readme.md) for a link.

**Comment by tomwayson** [comment] 2019-03-01 00:29
I'm pretty sure I got `externals` and `libtarget` working w/ webpack 4... somewhere... once.
